package:
  name: dgcv
  version: "0.1.2"

source:
  url: https://pypi.io/packages/source/d/dgcv/dgcv-0.1.0.tar.gz
  sha256: 7d8555800d2ad9322720ed0c3a49e2a00bbc611671d129c21a1b44c15b870851

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - sympy >=1.9
    - pandas >=1.0

test:
  imports:
    - dgcv

about:
  home: https://github.com/YikesItsSykes/DGCV
  license: MIT
  license_file: LICENSE  
  summary: "Differential Geometry with Complex Variables"
  description: |
    DGCV is a Python package that integrates basic tools for differential geometry 
    with systematic handling of complex variable-related structures.

extra:
  recipe-maintainers:
    - YikesItsSykes