package:
  name: dgcv
  version: "0.1.7"

source:
  url: https://files.pythonhosted.org/packages/22/23/bc2646f73108b1d3712ae2b9a6b43b178be85e2ffdf6c585971a11563462/dgcv-0.1.6.tar.gz
  sha256: 7657410252da990d546a7c3197774df2e816dc676acd5d73d816f0bee2530664

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - sympy >=1.9
    - pandas >=1.0
    - ipython >=7.0

test:
  imports:
    - dgcv

about:
  home: https://github.com/YikesItsSykes/DGCV
  license: MIT
  license_file: LICENSE  
  summary: "Differential Geometry with Complex Variables"
  description: |
    DGCV is a Python package that integrates tools for differential geometry 
    with systematic handling of complex variable-related structures.

extra:
  recipe-maintainers:
    - YikesItsSykes
