package:
  name: dgcv
  version: "0.1.2" 

source:
  url: https://files.pythonhosted.org/packages/86/54/dae949db12e1d3e61895006870e4922f4d54db25d979f7d42d95e8c6b5ea/dgcv-0.1.2.tar.gz  # Replace this with your actual PyPI tarball URL
  sha256: 7d8555800d2ad9322720ed0c3a49e2a00bbc611671d129c21a1b44c15b870851  # Update with correct checksum  # The checksum of the tarball to verify integrity

build:
  noarch: python  # Means this package works across platforms
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # Use pip to install your package

requirements:
  build:
    - python  # Python is required for building
    - pip     # Pip is needed to install the package
  host:
    - python
    - pip
  run:
    - python  # This is the minimum runtime requirement (e.g., python >=3.7 if needed)
    - sympy >=1.9  # Specify SymPy as a dependency
    - pandas >=1.0  # Specify Pandas as a dependency

about:
  home: https://github.com/YikesItsSykes/DGCV  # Link to the GitHub repository
  license: MIT  # License type
  summary: "Differential Geometry with Complex Variables"  # Short summary of the package
  description: |
    DGCV is a Python package that integrates basic tools for differential geometry 
    with systematic handling of complex variable-related structures.
  dev_url: https://github.com/YikesItsSykes/DGCV

extra:
  recipe-maintainers:
    - YikesItsSykes  # Your GitHub or Conda-forge username